twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true

        services:
    Twig\Environment:
        calls:
            - method: addExtension
              arguments:
                  - '@Symfony\Bridge\Twig\Extension\FormExtension'